import SwiftUI

extension Color {
    static let brandAccent      = Color(red: 0.784, green: 1.000, blue: 0.000) // #C8FF00
    static let brandBackground  = Color(red: 0.000, green: 0.000, blue: 0.000) // #000000
    static let brandPrimaryText = Color(red: 1.000, green: 1.000, blue: 1.000) // #FFFFFF
    // brandSecondary (#7D7D7D) auto-generated by Xcode from Colors/BrandSecondary asset
}
